- name: 開発ツールのインストール
  become: yes
  yum: name='@Development Tools'

- name: curlのインストール
  become: yes
  yum:
    name='curl'

- name: yum Repository ius インストール
  become: yes
  shell:
    curl -s https://setup.ius.io | sh
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register:
    result_ius
  changed_when: false
  failed_when: result_ius.rc not in [0, 1]

- name: gitのアンインストール
  become: yes
  yum:
    name='git'
    state=absent

- name: gitのインストール
  become: yes
  yum:
    name='git2u'

- name: yum Repository wandisco インストール
  become: yes
  template:
    src=wandisco.repo
    dest=/etc/yum.repos.d/wandisco.repo
    force=no

- name: yum Repository wandisco key インストール
  rpm_key:
    key: "http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco"

- name: subversionのインストール
  become: yes
  yum: enablerepo=wandisco-svn
    name='subversion'

- name: そのほかのツールのインストール
  become: yes
  yum:
    name='which,wget,openssl,openssl-devel,zlib,zlib-devel'

- name: 作業ディレクトリ作成
  file: path={{ work_dir }}
    state=directory
    mode=0755

